using System.Globalization;
using System.Text;

namespace GlobalSauce.Rendertargets
{
    public class ckeditorRenderer : IRenderTarget
    {
        public string Render(CultureInfo cultureInfo)
        {
            var ckeditorCulture = new StringBuilder();
            ckeditorCulture.AppendLine("/*");
            ckeditorCulture.AppendLine("Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.");
            ckeditorCulture.AppendLine("For licensing, see LICENSE.html or http://ckeditor.com/license");
            ckeditorCulture.AppendLine("*/");
            ckeditorCulture.AppendFormat("CKEDITOR.lang['{0}'] = {{\n", cultureInfo.Name);
            ckeditorCulture.AppendFormat("\"editor\": \"{0}\",\n", Resources.ckeditor.editor);
            ckeditorCulture.AppendLine("\"common\": {");
            ckeditorCulture.AppendFormat("\"editorHelp\": \"{0}\",\n", Resources.ckeditor.common_editorhelp);
            ckeditorCulture.AppendFormat("\"browseServer\": \"{0}\",\n", Resources.ckeditor.common_browseServer);
            ckeditorCulture.AppendFormat("\"url\": \"{0}\",\n", Resources.ckeditor.common_url);
            ckeditorCulture.AppendFormat("\"protocol\": \"{0}\",\n", Resources.ckeditor.common_protocol);
            ckeditorCulture.AppendFormat("\"upload\": \"{0}\",\n", Resources.ckeditor.common_upload);
            ckeditorCulture.AppendFormat("\"uploadSubmit\": \"{0}\",\n", Resources.ckeditor.common_uploadSubmit);
            ckeditorCulture.AppendFormat("\"image\": \"{0}\",\n", Resources.ckeditor.common_image);
            ckeditorCulture.AppendFormat("\"flash\": \"{0}\",\n", Resources.ckeditor.common_flash);
            ckeditorCulture.AppendFormat("\"form\": \"{0}\",\n", Resources.ckeditor.common_form);
            ckeditorCulture.AppendFormat("\"checkbox\": \"{0}\",\n", Resources.ckeditor.common_checkbox);
            ckeditorCulture.AppendFormat("\"radio\": \"{0}\",\n", Resources.ckeditor.common_radio);
            ckeditorCulture.AppendFormat("\"textField\": \"{0}\",\n", Resources.ckeditor.common_textField);
            ckeditorCulture.AppendFormat("\"textarea\": \"{0}\",\n", Resources.ckeditor.common_textarea);
            ckeditorCulture.AppendFormat("\"hiddenField\": \"{0}\",\n", Resources.ckeditor.common_hiddenField);
            ckeditorCulture.AppendFormat("\"button\": \"{0}\",\n", Resources.ckeditor.common_button);
            ckeditorCulture.AppendFormat("\"select\": \"{0}\",\n", Resources.ckeditor.common_select);
            ckeditorCulture.AppendFormat("\"imageButton\": \"{0}\",\n", Resources.ckeditor.common_imageButton);
            ckeditorCulture.AppendFormat("\"notSet\": \"{0}\",\n", Resources.ckeditor.common_notset);
            ckeditorCulture.AppendFormat("\"id\": \"{0}\",\n", Resources.ckeditor.common_id);
            ckeditorCulture.AppendFormat("\"name\": \"{0}\",\n", Resources.ckeditor.common_name);
            ckeditorCulture.AppendFormat("\"langDir\": \"{0}\",\n", Resources.ckeditor.common_langDir);
            ckeditorCulture.AppendFormat("\"langDirLtr\": \"{0}\",\n", Resources.ckeditor.common_langDirLtr);
            ckeditorCulture.AppendFormat("\"langDirRtl\": \"{0}\",\n", Resources.ckeditor.common_langDirRtl);
            ckeditorCulture.AppendFormat("\"langCode\": \"{0}\",\n", Resources.ckeditor.common_langCode);
            ckeditorCulture.AppendFormat("\"longDescr\": \"{0}\",\n", Resources.ckeditor.common_longDescr);
            ckeditorCulture.AppendFormat("\"cssClass\": \"{0}\",\n", Resources.ckeditor.common_cssClass);
            ckeditorCulture.AppendFormat("\"advisoryTitle\": \"{0}\",\n", Resources.ckeditor.common_advisoryTitle);
            ckeditorCulture.AppendFormat("\"cssStyle\": \"{0}\",\n", Resources.ckeditor.common_cssStyle);
            ckeditorCulture.AppendFormat("\"ok\": \"{0}\",\n", Resources.ckeditor.common_ok);
            ckeditorCulture.AppendFormat("\"cancel\": \"{0}\",\n", Resources.ckeditor.common_cancel);
            ckeditorCulture.AppendFormat("\"close\": \"{0}\",\n", Resources.ckeditor.common_close);
            ckeditorCulture.AppendFormat("\"preview\": \"{0}\",\n", Resources.ckeditor.common_preview);
            ckeditorCulture.AppendFormat("\"resize\": \"{0}\",\n", Resources.ckeditor.common_resize);
            ckeditorCulture.AppendFormat("\"generalTab\": \"{0}\",\n", Resources.ckeditor.common_generalTab);
            ckeditorCulture.AppendFormat("\"advancedTab\": \"{0}\",\n", Resources.ckeditor.common_advancedTab);
            ckeditorCulture.AppendFormat("\"validateNumberFailed\": \"{0}\",\n", Resources.ckeditor.common_validateNumberFailed);
            ckeditorCulture.AppendFormat("\"confirmNewPage\": \"{0}\",\n", Resources.ckeditor.common_confirmNewPage);
            ckeditorCulture.AppendFormat("\"confirmCancel\": \"{0}\",\n", Resources.ckeditor.common_confirmCancel);
            ckeditorCulture.AppendFormat("\"options\": \"{0}\",\n", Resources.ckeditor.common_options);
            ckeditorCulture.AppendFormat("\"target\": \"{0}\",\n", Resources.ckeditor.common_target);
            ckeditorCulture.AppendFormat("\"targetNew\": \"{0}\",\n", Resources.ckeditor.common_targetNew);
            ckeditorCulture.AppendFormat("\"targetTop\": \"{0}\",\n", Resources.ckeditor.common_targetTop);
            ckeditorCulture.AppendFormat("\"targetSelf\": \"{0}\",\n", Resources.ckeditor.common_targetSelf);
            ckeditorCulture.AppendFormat("\"targetParent\": \"{0}\",\n", Resources.ckeditor.common_targetParent);
            ckeditorCulture.AppendFormat("\"langDirLTR\": \"{0}\",\n", Resources.ckeditor.common_langDirLtr);
            ckeditorCulture.AppendFormat("\"langDirRTL\": \"{0}\",\n", Resources.ckeditor.common_langDirRtl);
            ckeditorCulture.AppendFormat("\"styles\": \"{0}\",\n", Resources.ckeditor.common_styles);
            ckeditorCulture.AppendFormat("\"cssClasses\": \"{0}\",\n", Resources.ckeditor.common_cssClasses);
            ckeditorCulture.AppendFormat("\"width\": \"{0}\",\n", Resources.ckeditor.common_width);
            ckeditorCulture.AppendFormat("\"height\": \"{0}\",\n", Resources.ckeditor.common_height);
            ckeditorCulture.AppendFormat("\"align\": \"{0}\",\n", Resources.ckeditor.common_align);
            ckeditorCulture.AppendFormat("\"alignLeft\": \"{0}\",\n", Resources.ckeditor.common_alignLeft);
            ckeditorCulture.AppendFormat("\"alignRight\": \"{0}\",\n", Resources.ckeditor.common_alignRight);
            ckeditorCulture.AppendFormat("\"alignCenter\": \"{0}\",\n", Resources.ckeditor.common_alignCenter);
            ckeditorCulture.AppendFormat("\"alignTop\": \"{0}\",\n", Resources.ckeditor.common_alignTop);
            ckeditorCulture.AppendFormat("\"alignMiddle\": \"{0}\",\n", Resources.ckeditor.common_alignMiddle);
            ckeditorCulture.AppendFormat("\"alignBottom\": \"{0}\",\n", Resources.ckeditor.common_alignBottom);
            ckeditorCulture.AppendFormat("\"invalidValue\": \"{0}\",\n", Resources.ckeditor.common_invalidValue);
            ckeditorCulture.AppendFormat("\"invalidHeight\": \"{0}\",\n", Resources.ckeditor.common_invalidHeight);
            ckeditorCulture.AppendFormat("\"invalidWidth\": \"{0}\",\n", Resources.ckeditor.common_invalidWidth);
            ckeditorCulture.AppendFormat("\"invalidCssLength\": \"{0}\",\n", Resources.ckeditor.common_invalidCssLength);
            ckeditorCulture.AppendFormat("\"invalidHtmlLength\": \"{0}\",\n", Resources.ckeditor.common_invalidHtmlLength);
            ckeditorCulture.AppendFormat("\"invalidInlineStyle\": \"{0}\",\n", Resources.ckeditor.common_invalidInlineStyle);
            ckeditorCulture.AppendFormat("\"cssLengthTooltip\": \"{0}\",\n", Resources.ckeditor.common_cssLengthTooltip);
            ckeditorCulture.AppendFormat("\"unavailable\": \"{0}\",\n", Resources.ckeditor.common_unavailable);
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"about\": {");
            ckeditorCulture.AppendFormat("\"copy\": \"{0}\",\n", Resources.ckeditor.about_copy);
            ckeditorCulture.AppendFormat("\"dlgTitle\": \"{0}\",\n", Resources.ckeditor.about_dlgTitle);
            ckeditorCulture.AppendFormat("\"help\": \"{0}\",\n", Resources.ckeditor.about_help);
            ckeditorCulture.AppendFormat("\"moreInfo\": \"{0}\",\n", Resources.ckeditor.about_moreInfo);
            ckeditorCulture.AppendFormat("\"title\": \"{0}\",\n", Resources.ckeditor.about_title);
            ckeditorCulture.AppendFormat("\"userGuide\": \"{0}\",\n", Resources.ckeditor.about_userGuide);
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"basicstyles\": {");
            ckeditorCulture.AppendFormat("\"bold\": \"{0}\",\n", Resources.ckeditor.basicstyles_bold);
            ckeditorCulture.AppendFormat("\"italic\": \"{0}\",\n", Resources.ckeditor.basicstyles_italic);
            ckeditorCulture.AppendFormat("\"strike\": \"{0}\",\n", Resources.ckeditor.basicstyles_strike);
            ckeditorCulture.AppendFormat("\"subscript\": \"{0}\",\n", Resources.ckeditor.basicstyles_subscript);
            ckeditorCulture.AppendFormat("\"superscript\": \"{0}\",\n", Resources.ckeditor.basicstyles_superscript);
            ckeditorCulture.AppendFormat("\"underline\": \"{0}\",\n", Resources.ckeditor.basicstyles_underline);
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"clipboard\": {");
            ckeditorCulture.AppendFormat("\"copy\": \"{0}\",\n", Resources.ckeditor.clipboard_copy);
            ckeditorCulture.AppendFormat("\"copyError\": \"{0}\",\n", Resources.ckeditor.clipboard_copyError);
            ckeditorCulture.AppendFormat("\"cut\": \"{0}\",\n", Resources.ckeditor.clipboard_cut);
            ckeditorCulture.AppendFormat("\"cutError\": \"{0}\",\n", Resources.ckeditor.clipboard_cutError);
            ckeditorCulture.AppendFormat("\"paste\": \"{0}\",\n", Resources.ckeditor.clipboard_paste);
            ckeditorCulture.AppendFormat("\"pasteArea\": \"{0}\",\n", Resources.ckeditor.clipboard_pasteArea);
            ckeditorCulture.AppendFormat("\"pasteMsg\": \"{0}\",\n", Resources.ckeditor.clipboard_pasteMsg);
            ckeditorCulture.AppendFormat("\"securityMsg\": \"{0}\",\n", Resources.ckeditor.clipboard_securityMsg);
            ckeditorCulture.AppendFormat("\"title\": \"{0}\",\n", Resources.ckeditor.clipboard_title);
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"toolbar\": {");
            ckeditorCulture.AppendFormat("\"toolbarCollapse\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarCollapse);
            ckeditorCulture.AppendFormat("\"toolbarExpand\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarExpand);
            ckeditorCulture.AppendLine("\"toolbarGroups\": {");
            ckeditorCulture.AppendFormat("\"document\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_document);
            ckeditorCulture.AppendFormat("\"clipboard\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_clipboard);
            ckeditorCulture.AppendFormat("\"editing\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_editing);
            ckeditorCulture.AppendFormat("\"forms\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_forms);
            ckeditorCulture.AppendFormat("\"basicstyles\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_basicstyles);
            ckeditorCulture.AppendFormat("\"paragraph\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_paragraph);
            ckeditorCulture.AppendFormat("\"links\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_links);
            ckeditorCulture.AppendFormat("\"insert\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_insert);
            ckeditorCulture.AppendFormat("\"styles\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_styles);
            ckeditorCulture.AppendFormat("\"colors\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_colors);
            ckeditorCulture.AppendFormat("\"tools\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbarGroups_tools);
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendFormat("\"toolbars\": \"{0}\",\n", Resources.ckeditor.toolbar_toolbars);
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"indent\": {");
            ckeditorCulture.AppendFormat("\"indent\": \"{0}\",\n", Resources.ckeditor.indent_indent);
            ckeditorCulture.AppendFormat("\"outdent\": \"{0}\",\n", Resources.ckeditor.indent_outdent);
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"fakeobjects\": {");
            ckeditorCulture.AppendFormat("\"anchor\": \"{0}\",\n", Resources.ckeditor.fakeobjects_anchor);
            ckeditorCulture.AppendFormat("\"flash\": \"{0}\",\n", Resources.ckeditor.fakeobjects_flash);
            ckeditorCulture.AppendFormat("\"hiddenfield\": \"{0}\",\n", Resources.ckeditor.fakeobjects_hiddenfield);
            ckeditorCulture.AppendFormat("\"iframe\": \"{0}\",\n", Resources.ckeditor.fakeobjects_iframe);
            ckeditorCulture.AppendFormat("\"unknown\": \"{0}\",\n", Resources.ckeditor.fakeobjects_unknown);
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"link\": {");
            ckeditorCulture.AppendFormat("\"acccessKey\": \"{0}\",\n", Resources.ckeditor.link_acccessKey);
            ckeditorCulture.AppendFormat("\"advanced\": \"{0}\",\n", Resources.ckeditor.link_advanced);
            ckeditorCulture.AppendFormat("\"advisoryContentType\": \"{0}\",\n", Resources.ckeditor.link_advisoryContentType);
            ckeditorCulture.AppendFormat("\"advisoryTitle\": \"{0}\",\n", Resources.ckeditor.link_advisoryTitle);
            ckeditorCulture.AppendLine("\"anchor\": {");
            ckeditorCulture.AppendFormat("\"toolbar\": \"{0}\",\n", Resources.ckeditor.link_anchor_toolbar);
            ckeditorCulture.AppendFormat("\"menu\": \"{0}\",\n", Resources.ckeditor.link_anchor_menu);
            ckeditorCulture.AppendFormat("\"title\": \"{0}\",\n", Resources.ckeditor.link_anchor_title);
            ckeditorCulture.AppendFormat("\"name\": \"{0}\",\n", Resources.ckeditor.link_anchor_name);
            ckeditorCulture.AppendFormat("\"errorName\": \"{0}\",\n", Resources.ckeditor.link_anchor_errorName);
            ckeditorCulture.AppendFormat("\"remove\": \"{0}\",\n", Resources.ckeditor.link_anchor_remove);
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"anchorId\": \"By Element Id\",");
            ckeditorCulture.AppendLine("\"anchorName\": \"By Anchor Name\",");
            ckeditorCulture.AppendLine("\"charset\": \"Linked Resource Charset\",");
            ckeditorCulture.AppendLine("\"cssClasses\": \"Stylesheet Classes\",");
            ckeditorCulture.AppendLine("\"emailAddress\": \"E-Mail Address\",");
            ckeditorCulture.AppendLine("\"emailBody\": \"Message Body\",");
            ckeditorCulture.AppendLine("\"emailSubject\": \"Message Subject\",");
            ckeditorCulture.AppendLine("\"id\": \"Id\",");
            ckeditorCulture.AppendLine("\"info\": \"Link Info\",");
            ckeditorCulture.AppendLine("\"langCode\": \"Language Code\",");
            ckeditorCulture.AppendLine("\"langDir\": \"Language Direction\",");
            ckeditorCulture.AppendLine("\"langDirLTR\": \"Left to Right (LTR)\",");
            ckeditorCulture.AppendLine("\"langDirRTL\": \"Right to Left (RTL)\",");
            ckeditorCulture.AppendLine("\"menu\": \"Edit Link\",");
            ckeditorCulture.AppendLine("\"name\": \"Name\",");
            ckeditorCulture.AppendLine("\"noAnchors\": \"(No anchors available in the document)\",");
            ckeditorCulture.AppendLine("\"noEmail\": \"Please type the e-mail address\",");
            ckeditorCulture.AppendLine("\"noUrl\": \"Please type the link URL\",");
            ckeditorCulture.AppendLine("\"other\": \"<other>\",");
            ckeditorCulture.AppendLine("\"popupDependent\": \"Dependent (Netscape)\",");
            ckeditorCulture.AppendLine("\"popupFeatures\": \"Popup Window Features\",");
            ckeditorCulture.AppendLine("\"popupFullScreen\": \"Full Screen (IE)\",");
            ckeditorCulture.AppendLine("\"popupLeft\": \"Left Position\",");
            ckeditorCulture.AppendLine("\"popupLocationBar\": \"Location Bar\",");
            ckeditorCulture.AppendLine("\"popupMenuBar\": \"Menu Bar\",");
            ckeditorCulture.AppendLine("\"popupResizable\": \"Resizable\",");
            ckeditorCulture.AppendLine("\"popupScrollBars\": \"Scroll Bars\",");
            ckeditorCulture.AppendLine("\"popupStatusBar\": \"Status Bar\",");
            ckeditorCulture.AppendLine("\"popupToolbar\": \"Toolbar\",");
            ckeditorCulture.AppendLine("\"popupTop\": \"Top Position\",");
            ckeditorCulture.AppendLine("\"rel\": \"Relationship\",");
            ckeditorCulture.AppendLine("\"selectAnchor\": \"Select an Anchor\",");
            ckeditorCulture.AppendLine("\"styles\": \"Style\",");
            ckeditorCulture.AppendLine("\"tabIndex\": \"Tab Index\",");
            ckeditorCulture.AppendLine("\"target\": \"Target\",");
            ckeditorCulture.AppendLine("\"targetFrame\": \"<frame>\",");
            ckeditorCulture.AppendLine("\"targetFrameName\": \"Target Frame Name\",");
            ckeditorCulture.AppendLine("\"targetPopup\": \"<popup window>\",");
            ckeditorCulture.AppendLine("\"targetPopupName\": \"Popup Window Name\",");
            ckeditorCulture.AppendLine("\"title\": \"Link\",");
            ckeditorCulture.AppendLine("\"toAnchor\": \"Link to anchor in the text\",");
            ckeditorCulture.AppendLine("\"toEmail\": \"E-mail\",");
            ckeditorCulture.AppendLine("\"toUrl\": \"URL\",");
            ckeditorCulture.AppendLine("\"toolbar\": \"Link\",");
            ckeditorCulture.AppendLine("\"type\": \"Link Type\",");
            ckeditorCulture.AppendLine("\"unlink\": \"Unlink\",");
            ckeditorCulture.AppendLine("\"upload\": \"Upload\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"list\": {");
            ckeditorCulture.AppendLine("\"bulletedlist\": \"Insert/Remove Bulleted List\",");
            ckeditorCulture.AppendLine("\"numberedlist\": \"Insert/Remove Numbered List\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"undo\": {");
            ckeditorCulture.AppendLine("\"redo\": \"Redo\",");
            ckeditorCulture.AppendLine("\"undo\": \"Undo\"");
            ckeditorCulture.AppendLine(" }");
            ckeditorCulture.AppendLine("};");

            return ckeditorCulture.ToString();
        }
    }
}
