using System.Globalization;
using System.Text;

namespace GlobalSauce.Rendertargets
{
    public class ckeditorRenderer : IRenderTarget
    {
        public string Render(CultureInfo cultureInfo)
        {
            var ckeditorCulture = new StringBuilder();
            ckeditorCulture.AppendLine("/*");
            ckeditorCulture.AppendLine("Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.");
            ckeditorCulture.AppendLine("For licensing, see LICENSE.html or http://ckeditor.com/license");
            ckeditorCulture.AppendLine("*/");
            ckeditorCulture.AppendLine("CKEDITOR.lang['en'] = {");
            ckeditorCulture.AppendLine("\"editor\": \"Rich Text Editor\",");
            ckeditorCulture.AppendLine("\"common\": {");
            ckeditorCulture.AppendLine("\"editorHelp\": \"Press ALT 0 for help\",");
            ckeditorCulture.AppendLine("\"browseServer\": \"Browse Server\",");
            ckeditorCulture.AppendLine("\"url\": \"URL\",");
            ckeditorCulture.AppendLine("\"protocol\": \"Protocol\",");
            ckeditorCulture.AppendLine("\"upload\": \"Upload\",");
            ckeditorCulture.AppendLine("\"uploadSubmit\": \"Send it to the Server\",");
            ckeditorCulture.AppendLine("\"image\": \"Image\",");
            ckeditorCulture.AppendLine("\"flash\": \"Flash\",");
            ckeditorCulture.AppendLine("\"form\": \"Form\",");
            ckeditorCulture.AppendLine("\"checkbox\": \"Checkbox\",");
            ckeditorCulture.AppendLine("\"radio\": \"Radio Button\",");
            ckeditorCulture.AppendLine("\"textField\": \"Text Field\",");
            ckeditorCulture.AppendLine("\"textarea\": \"Textarea\",");
            ckeditorCulture.AppendLine("\"hiddenField\": \"Hidden Field\",");
            ckeditorCulture.AppendLine("\"button\": \"Button\",");
            ckeditorCulture.AppendLine("\"select\": \"Selection Field\",");
            ckeditorCulture.AppendLine("\"imageButton\": \"Image Button\",");
            ckeditorCulture.AppendLine("\"notSet\": \"<not set>\",");
            ckeditorCulture.AppendLine("\"id\": \"Id\",");
            ckeditorCulture.AppendLine("\"name\": \"Name\",");
            ckeditorCulture.AppendLine("\"langDir\": \"Language Direction\",");
            ckeditorCulture.AppendLine("\"langDirLtr\": \"Left to Right (LTR)\",");
            ckeditorCulture.AppendLine("\"langDirRtl\": \"Right to Left (RTL)\",");
            ckeditorCulture.AppendLine("\"langCode\": \"Language Code\",");
            ckeditorCulture.AppendLine("\"longDescr\": \"Long Description URL\",");
            ckeditorCulture.AppendLine("\"cssClass\": \"Stylesheet Classes\",");
            ckeditorCulture.AppendLine("\"advisoryTitle\": \"Advisory Title\",");
            ckeditorCulture.AppendLine("\"cssStyle\": \"Style\",");
            ckeditorCulture.AppendLine("\"ok\": \"OK\",");
            ckeditorCulture.AppendLine("\"cancel\": \"Cancel\",");
            ckeditorCulture.AppendLine("\"close\": \"Close\",");
            ckeditorCulture.AppendLine("\"preview\": \"Preview\",");
            ckeditorCulture.AppendLine("\"resize\": \"Resize\",");
            ckeditorCulture.AppendLine("\"generalTab\": \"General\",");
            ckeditorCulture.AppendLine("\"advancedTab\": \"Advanced\",");
            ckeditorCulture.AppendLine("\"validateNumberFailed\": \"This value is not a number.\",");
            ckeditorCulture.AppendLine("\"confirmNewPage\": \"Any unsaved changes to this content will be lost. Are you sure you want to load new page?\",");
            ckeditorCulture.AppendLine("\"confirmCancel\": \"Some of the options have been changed. Are you sure to close the dialog?\",");
            ckeditorCulture.AppendLine("\"options\": \"Options\",");
            ckeditorCulture.AppendLine("\"target\": \"Target\",");
            ckeditorCulture.AppendLine("\"targetNew\": \"New Window (_blank)\",");
            ckeditorCulture.AppendLine("\"targetTop\": \"Topmost Window (_top)\",");
            ckeditorCulture.AppendLine("\"targetSelf\": \"Same Window (_self)\",");
            ckeditorCulture.AppendLine("\"targetParent\": \"Parent Window (_parent)\",");
            ckeditorCulture.AppendLine("\"langDirLTR\": \"Left to Right (LTR)\",");
            ckeditorCulture.AppendLine("\"langDirRTL\": \"Right to Left (RTL)\",");
            ckeditorCulture.AppendLine("\"styles\": \"Style\",");
            ckeditorCulture.AppendLine("\"cssClasses\": \"Stylesheet Classes\",");
            ckeditorCulture.AppendLine("\"width\": \"Width\",");
            ckeditorCulture.AppendLine("\"height\": \"Height\",");
            ckeditorCulture.AppendLine("\"align\": \"Alignment\",");
            ckeditorCulture.AppendLine("\"alignLeft\": \"Left\",");
            ckeditorCulture.AppendLine("\"alignRight\": \"Right\",");
            ckeditorCulture.AppendLine("\"alignCenter\": \"Center\",");
            ckeditorCulture.AppendLine("\"alignTop\": \"Top\",");
            ckeditorCulture.AppendLine("\"alignMiddle\": \"Middle\",");
            ckeditorCulture.AppendLine("\"alignBottom\": \"Bottom\",");
            ckeditorCulture.AppendLine("\"invalidValue\": \"Invalid value.\",");
            ckeditorCulture.AppendLine("\"invalidHeight\": \"Height must be a number.\",");
            ckeditorCulture.AppendLine("\"invalidWidth\": \"Width must be a number.\",");
            ckeditorCulture.AppendLine("\"invalidCssLength\": \"Value specified for the \"%1\" field must be a positive number with or without a valid CSS measurement unit (px, %, in, cm, mm, em, ex, pt, or pc).\",");
            ckeditorCulture.AppendLine("\"invalidHtmlLength\": \"Value specified for the \"%1\" field must be a positive number with or without a valid HTML measurement unit (px or %).\",");
            ckeditorCulture.AppendLine("\"invalidInlineStyle\": \"Value specified for the inline style must consist of one or more tuples with the format of \"name : value\", " + "separated by semi-colons.\",");
            ckeditorCulture.AppendLine("\"cssLengthTooltip\": \"Enter a number for a value in pixels or a number with a valid CSS unit (px, %, in, cm, mm, em, ex, pt, or pc).\",");
            ckeditorCulture.AppendLine("\"unavailable\": \"%1<span class=\"cke_accessibility\">, unavailable</span>\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"about\": {");
            ckeditorCulture.AppendLine("\"copy\": \"Copyright &copy; $1. All rights reserved.\",");
            ckeditorCulture.AppendLine("\"dlgTitle\": \"About CKEditor\",");
            ckeditorCulture.AppendLine("\"help\": \"Check $1 for help.\",");
            ckeditorCulture.AppendLine("\"moreInfo\": \"For licensing information please visit our web site:\",");
            ckeditorCulture.AppendLine("\"title\": \"About CKEditor\",");
            ckeditorCulture.AppendLine("\"userGuide\": \"CKEditor User's Guide\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"basicstyles\": {");
            ckeditorCulture.AppendLine("\"bold\": \"Bold\",");
            ckeditorCulture.AppendLine("\"italic\": \"Italic\",");
            ckeditorCulture.AppendLine("\"strike\": \"Strike Through\",");
            ckeditorCulture.AppendLine("\"subscript\": \"Subscript\",");
            ckeditorCulture.AppendLine("\"superscript\": \"Superscript\",");
            ckeditorCulture.AppendLine("\"underline\": \"Underline\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"clipboard\": {");
            ckeditorCulture.AppendLine("\"copy\": \"Copy\",");
            ckeditorCulture.AppendLine("\"copyError\": \"Your browser security settings don't permit the editor to automatically execute copying operations. Please use the keyboard for that (Ctrl/Cmd+C).\",");
            ckeditorCulture.AppendLine("\"cut\": \"Cut\",");
            ckeditorCulture.AppendLine("\"cutError\": \"Your browser security settings don't permit the editor to automatically execute cutting operations. Please use the keyboard for that (Ctrl/Cmd+X).\",");
            ckeditorCulture.AppendLine("\"paste\": \"Paste\",");
            ckeditorCulture.AppendLine("\"pasteArea\": \"Paste Area\",");
            ckeditorCulture.AppendLine("\"pasteMsg\": \"Please paste inside the following box using the keyboard (<strong>Ctrl/Cmd+V</strong>) and hit OK\",");
            ckeditorCulture.AppendLine("\"securityMsg\": \"Because of your browser security settings, the editor is not able to access your clipboard data directly. You are required to paste it again in this window.\",");
            ckeditorCulture.AppendLine("\"title\": \"Paste\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"toolbar\": {");
            ckeditorCulture.AppendLine("\"toolbarCollapse\": \"Collapse Toolbar\",");
            ckeditorCulture.AppendLine("\"toolbarExpand\": \"Expand Toolbar\",");
            ckeditorCulture.AppendLine("\"toolbarGroups\": {");
            ckeditorCulture.AppendLine("\"document\": \"Document\",");
            ckeditorCulture.AppendLine("\"clipboard\": \"Clipboard/Undo\",");
            ckeditorCulture.AppendLine("\"editing\": \"Editing\",");
            ckeditorCulture.AppendLine("\"forms\": \"Forms\",");
            ckeditorCulture.AppendLine("\"basicstyles\": \"Basic Styles\",");
            ckeditorCulture.AppendLine("\"paragraph\": \"Paragraph\",");
            ckeditorCulture.AppendLine("\"links\": \"Links\",");
            ckeditorCulture.AppendLine("\"insert\": \"Insert\",");
            ckeditorCulture.AppendLine("\"styles\": \"Styles\",");
            ckeditorCulture.AppendLine("\"colors\": \"Colors\",");
            ckeditorCulture.AppendLine("\"tools\": \"Tools\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"toolbars\": \"Editor toolbars\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"indent\": {");
            ckeditorCulture.AppendLine("\"indent\": \"Increase Indent\",");
            ckeditorCulture.AppendLine("\"outdent\": \"Decrease Indent\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"fakeobjects\": {");
            ckeditorCulture.AppendLine("\"anchor\": \"Anchor\",");
            ckeditorCulture.AppendLine("\"flash\": \"Flash Animation\",");
            ckeditorCulture.AppendLine("\"hiddenfield\": \"Hidden Field\",");
            ckeditorCulture.AppendLine("\"iframe\": \"IFrame\",");
            ckeditorCulture.AppendLine("\"unknown\": \"Unknown Object\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"link\": {");
            ckeditorCulture.AppendLine("\"acccessKey\": \"Access Key\",");
            ckeditorCulture.AppendLine("\"advanced\": \"Advanced\",");
            ckeditorCulture.AppendLine("\"advisoryContentType\": \"Advisory Content Type\",");
            ckeditorCulture.AppendLine("\"advisoryTitle\": \"Advisory Title\",");
            ckeditorCulture.AppendLine("\"anchor\": {");
            ckeditorCulture.AppendLine("\"toolbar\": \"Anchor\",");
            ckeditorCulture.AppendLine("\"menu\": \"Edit Anchor\",");
            ckeditorCulture.AppendLine("\"title\": \"Anchor Properties\",");
            ckeditorCulture.AppendLine("\"name\": \"Anchor Name\",");
            ckeditorCulture.AppendLine("\"errorName\": \"Please type the anchor name\",");
            ckeditorCulture.AppendLine("\"remove\": \"Remove Anchor\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"anchorId\": \"By Element Id\",");
            ckeditorCulture.AppendLine("\"anchorName\": \"By Anchor Name\",");
            ckeditorCulture.AppendLine("\"charset\": \"Linked Resource Charset\",");
            ckeditorCulture.AppendLine("\"cssClasses\": \"Stylesheet Classes\",");
            ckeditorCulture.AppendLine("\"emailAddress\": \"E-Mail Address\",");
            ckeditorCulture.AppendLine("\"emailBody\": \"Message Body\",");
            ckeditorCulture.AppendLine("\"emailSubject\": \"Message Subject\",");
            ckeditorCulture.AppendLine("\"id\": \"Id\",");
            ckeditorCulture.AppendLine("\"info\": \"Link Info\",");
            ckeditorCulture.AppendLine("\"langCode\": \"Language Code\",");
            ckeditorCulture.AppendLine("\"langDir\": \"Language Direction\",");
            ckeditorCulture.AppendLine("\"langDirLTR\": \"Left to Right (LTR)\",");
            ckeditorCulture.AppendLine("\"langDirRTL\": \"Right to Left (RTL)\",");
            ckeditorCulture.AppendLine("\"menu\": \"Edit Link\",");
            ckeditorCulture.AppendLine("\"name\": \"Name\",");
            ckeditorCulture.AppendLine("\"noAnchors\": \"(No anchors available in the document)\",");
            ckeditorCulture.AppendLine("\"noEmail\": \"Please type the e-mail address\",");
            ckeditorCulture.AppendLine("\"noUrl\": \"Please type the link URL\",");
            ckeditorCulture.AppendLine("\"other\": \"<other>\",");
            ckeditorCulture.AppendLine("\"popupDependent\": \"Dependent (Netscape)\",");
            ckeditorCulture.AppendLine("\"popupFeatures\": \"Popup Window Features\",");
            ckeditorCulture.AppendLine("\"popupFullScreen\": \"Full Screen (IE)\",");
            ckeditorCulture.AppendLine("\"popupLeft\": \"Left Position\",");
            ckeditorCulture.AppendLine("\"popupLocationBar\": \"Location Bar\",");
            ckeditorCulture.AppendLine("\"popupMenuBar\": \"Menu Bar\",");
            ckeditorCulture.AppendLine("\"popupResizable\": \"Resizable\",");
            ckeditorCulture.AppendLine("\"popupScrollBars\": \"Scroll Bars\",");
            ckeditorCulture.AppendLine("\"popupStatusBar\": \"Status Bar\",");
            ckeditorCulture.AppendLine("\"popupToolbar\": \"Toolbar\",");
            ckeditorCulture.AppendLine("\"popupTop\": \"Top Position\",");
            ckeditorCulture.AppendLine("\"rel\": \"Relationship\",");
            ckeditorCulture.AppendLine("\"selectAnchor\": \"Select an Anchor\",");
            ckeditorCulture.AppendLine("\"styles\": \"Style\",");
            ckeditorCulture.AppendLine("\"tabIndex\": \"Tab Index\",");
            ckeditorCulture.AppendLine("\"target\": \"Target\",");
            ckeditorCulture.AppendLine("\"targetFrame\": \"<frame>\",");
            ckeditorCulture.AppendLine("\"targetFrameName\": \"Target Frame Name\",");
            ckeditorCulture.AppendLine("\"targetPopup\": \"<popup window>\",");
            ckeditorCulture.AppendLine("\"targetPopupName\": \"Popup Window Name\",");
            ckeditorCulture.AppendLine("\"title\": \"Link\",");
            ckeditorCulture.AppendLine("\"toAnchor\": \"Link to anchor in the text\",");
            ckeditorCulture.AppendLine("\"toEmail\": \"E-mail\",");
            ckeditorCulture.AppendLine("\"toUrl\": \"URL\",");
            ckeditorCulture.AppendLine("\"toolbar\": \"Link\",");
            ckeditorCulture.AppendLine("\"type\": \"Link Type\",");
            ckeditorCulture.AppendLine("\"unlink\": \"Unlink\",");
            ckeditorCulture.AppendLine("\"upload\": \"Upload\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"list\": {");
            ckeditorCulture.AppendLine("\"bulletedlist\": \"Insert/Remove Bulleted List\",");
            ckeditorCulture.AppendLine("\"numberedlist\": \"Insert/Remove Numbered List\"");
            ckeditorCulture.AppendLine("},");
            ckeditorCulture.AppendLine("\"undo\": {");
            ckeditorCulture.AppendLine("\"redo\": \"Redo\",");
            ckeditorCulture.AppendLine("\"undo\": \"Undo\"");
            ckeditorCulture.AppendLine(" }");
            ckeditorCulture.AppendLine("};");

            return ckeditorCulture.ToString();
        }
    }
}
