//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSauce.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ckeditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ckeditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalSauce.Resources.ckeditor", typeof(ckeditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy; $1. All rights reserved..
        /// </summary>
        internal static string about_copy {
            get {
                return ResourceManager.GetString("about_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About CKEditor.
        /// </summary>
        internal static string about_dlgTitle {
            get {
                return ResourceManager.GetString("about_dlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check $1 for help..
        /// </summary>
        internal static string about_help {
            get {
                return ResourceManager.GetString("about_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For licensing information please visit our web site:.
        /// </summary>
        internal static string about_moreInfo {
            get {
                return ResourceManager.GetString("about_moreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About CKEditor.
        /// </summary>
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CKEditor User&apos;s Guide.
        /// </summary>
        internal static string about_userGuide {
            get {
                return ResourceManager.GetString("about_userGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string basicstyles_bold {
            get {
                return ResourceManager.GetString("basicstyles_bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string basicstyles_italic {
            get {
                return ResourceManager.GetString("basicstyles_italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strike Through.
        /// </summary>
        internal static string basicstyles_strike {
            get {
                return ResourceManager.GetString("basicstyles_strike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscripts.
        /// </summary>
        internal static string basicstyles_subscript {
            get {
                return ResourceManager.GetString("basicstyles_subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        internal static string basicstyles_superscript {
            get {
                return ResourceManager.GetString("basicstyles_superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string basicstyles_underline {
            get {
                return ResourceManager.GetString("basicstyles_underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string clipboard_copy {
            get {
                return ResourceManager.GetString("clipboard_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser security settings don&apos;t permit the editor to automatically execute copying operations. Please use the keyboard for that (Ctrl/Cmd+C)..
        /// </summary>
        internal static string clipboard_copyError {
            get {
                return ResourceManager.GetString("clipboard_copyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string clipboard_cut {
            get {
                return ResourceManager.GetString("clipboard_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser security settings don&apos;t permit the editor to automatically execute cutting operations. Please use the keyboard for that (Ctrl/Cmd+X)..
        /// </summary>
        internal static string clipboard_cutError {
            get {
                return ResourceManager.GetString("clipboard_cutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string clipboard_paste {
            get {
                return ResourceManager.GetString("clipboard_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Area.
        /// </summary>
        internal static string clipboard_pasteArea {
            get {
                return ResourceManager.GetString("clipboard_pasteArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste inside the following box using the keyboard (&lt;strong&gt;Ctrl/Cmd+V&lt;/strong&gt;) and hit OK.
        /// </summary>
        internal static string clipboard_pasteMsg {
            get {
                return ResourceManager.GetString("clipboard_pasteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of your browser security settings, the editor is not able to access your clipboard data directly. You are required to paste it again in this window..
        /// </summary>
        internal static string clipboard_securityMsg {
            get {
                return ResourceManager.GetString("clipboard_securityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string clipboard_title {
            get {
                return ResourceManager.GetString("clipboard_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string common_advancedTab {
            get {
                return ResourceManager.GetString("common_advancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory Title.
        /// </summary>
        internal static string common_advisoryTitle {
            get {
                return ResourceManager.GetString("common_advisoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string common_align {
            get {
                return ResourceManager.GetString("common_align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string common_alignBottom {
            get {
                return ResourceManager.GetString("common_alignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string common_alignCenter {
            get {
                return ResourceManager.GetString("common_alignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string common_alignLeft {
            get {
                return ResourceManager.GetString("common_alignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string common_alignMiddle {
            get {
                return ResourceManager.GetString("common_alignMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string common_alignRight {
            get {
                return ResourceManager.GetString("common_alignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string common_alignTop {
            get {
                return ResourceManager.GetString("common_alignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Server.
        /// </summary>
        internal static string common_browseServer {
            get {
                return ResourceManager.GetString("common_browseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string common_button {
            get {
                return ResourceManager.GetString("common_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string common_cancel {
            get {
                return ResourceManager.GetString("common_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox.
        /// </summary>
        internal static string common_checkbox {
            get {
                return ResourceManager.GetString("common_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string common_close {
            get {
                return ResourceManager.GetString("common_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the options have been changed. Are you sure to close the dialog?.
        /// </summary>
        internal static string common_confirmCancel {
            get {
                return ResourceManager.GetString("common_confirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any unsaved changes to this content will be lost. Are you sure you want to load new page?.
        /// </summary>
        internal static string common_confirmNewPage {
            get {
                return ResourceManager.GetString("common_confirmNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylesheet Classes.
        /// </summary>
        internal static string common_cssClass {
            get {
                return ResourceManager.GetString("common_cssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylesheet Classes.
        /// </summary>
        internal static string common_cssClasses {
            get {
                return ResourceManager.GetString("common_cssClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number for a value in pixels or a number with a valid CSS unit (px, %, in, cm, mm, em, ex, pt, or pc)..
        /// </summary>
        internal static string common_cssLengthTooltip {
            get {
                return ResourceManager.GetString("common_cssLengthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string common_cssStyle {
            get {
                return ResourceManager.GetString("common_cssStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ALT 0 for help.
        /// </summary>
        internal static string common_editorhelp {
            get {
                return ResourceManager.GetString("common_editorhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        internal static string common_flash {
            get {
                return ResourceManager.GetString("common_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string common_form {
            get {
                return ResourceManager.GetString("common_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string common_generalTab {
            get {
                return ResourceManager.GetString("common_generalTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string common_height {
            get {
                return ResourceManager.GetString("common_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Field.
        /// </summary>
        internal static string common_hiddenField {
            get {
                return ResourceManager.GetString("common_hiddenField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string common_id {
            get {
                return ResourceManager.GetString("common_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string common_image {
            get {
                return ResourceManager.GetString("common_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Button.
        /// </summary>
        internal static string common_imageButton {
            get {
                return ResourceManager.GetString("common_imageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value specified for the \&quot;%1\&quot; field must be a positive number with or without a valid CSS measurement unit (px, %, in, cm, mm, em, ex, pt, or pc)..
        /// </summary>
        internal static string common_invalidCssLength {
            get {
                return ResourceManager.GetString("common_invalidCssLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must be a number..
        /// </summary>
        internal static string common_invalidHeight {
            get {
                return ResourceManager.GetString("common_invalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value specified for the \&quot;%1\&quot; field must be a positive number with or without a valid HTML measurement unit (px or %)..
        /// </summary>
        internal static string common_invalidHtmlLength {
            get {
                return ResourceManager.GetString("common_invalidHtmlLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value specified for the inline style must consist of one or more tuples with the format of \&quot;name : value\&quot;, \&quot; + \&quot;separated by semi-colons..
        /// </summary>
        internal static string common_invalidInlineStyle {
            get {
                return ResourceManager.GetString("common_invalidInlineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value..
        /// </summary>
        internal static string common_invalidValue {
            get {
                return ResourceManager.GetString("common_invalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width must be a number..
        /// </summary>
        internal static string common_invalidWidth {
            get {
                return ResourceManager.GetString("common_invalidWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Code.
        /// </summary>
        internal static string common_langCode {
            get {
                return ResourceManager.GetString("common_langCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Direction.
        /// </summary>
        internal static string common_langDir {
            get {
                return ResourceManager.GetString("common_langDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left to Right (LTR).
        /// </summary>
        internal static string common_langDirLtr {
            get {
                return ResourceManager.GetString("common_langDirLtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Left (RTL).
        /// </summary>
        internal static string common_langDirRtl {
            get {
                return ResourceManager.GetString("common_langDirRtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Description URL.
        /// </summary>
        internal static string common_longDescr {
            get {
                return ResourceManager.GetString("common_longDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string common_name {
            get {
                return ResourceManager.GetString("common_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;not set&gt;.
        /// </summary>
        internal static string common_notset {
            get {
                return ResourceManager.GetString("common_notset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string common_ok {
            get {
                return ResourceManager.GetString("common_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string common_options {
            get {
                return ResourceManager.GetString("common_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string common_preview {
            get {
                return ResourceManager.GetString("common_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string common_protocol {
            get {
                return ResourceManager.GetString("common_protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Button.
        /// </summary>
        internal static string common_radio {
            get {
                return ResourceManager.GetString("common_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        internal static string common_resize {
            get {
                return ResourceManager.GetString("common_resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Field.
        /// </summary>
        internal static string common_select {
            get {
                return ResourceManager.GetString("common_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string common_styles {
            get {
                return ResourceManager.GetString("common_styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string common_target {
            get {
                return ResourceManager.GetString("common_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Window (_blank).
        /// </summary>
        internal static string common_targetNew {
            get {
                return ResourceManager.GetString("common_targetNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Window (_parent).
        /// </summary>
        internal static string common_targetParent {
            get {
                return ResourceManager.GetString("common_targetParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Window (_self).
        /// </summary>
        internal static string common_targetSelf {
            get {
                return ResourceManager.GetString("common_targetSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topmost Window (_top).
        /// </summary>
        internal static string common_targetTop {
            get {
                return ResourceManager.GetString("common_targetTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textarea.
        /// </summary>
        internal static string common_textarea {
            get {
                return ResourceManager.GetString("common_textarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Field.
        /// </summary>
        internal static string common_textField {
            get {
                return ResourceManager.GetString("common_textField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1&lt;span class=\&quot;cke_accessibility\&quot;&gt;, unavailable&lt;/span&gt;.
        /// </summary>
        internal static string common_unavailable {
            get {
                return ResourceManager.GetString("common_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string common_upload {
            get {
                return ResourceManager.GetString("common_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send it to the Server.
        /// </summary>
        internal static string common_uploadSubmit {
            get {
                return ResourceManager.GetString("common_uploadSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string common_url {
            get {
                return ResourceManager.GetString("common_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is not a number..
        /// </summary>
        internal static string common_validateNumberFailed {
            get {
                return ResourceManager.GetString("common_validateNumberFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string common_width {
            get {
                return ResourceManager.GetString("common_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Editor.
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        internal static string fakeobjects_anchor {
            get {
                return ResourceManager.GetString("fakeobjects_anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Animation.
        /// </summary>
        internal static string fakeobjects_flash {
            get {
                return ResourceManager.GetString("fakeobjects_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Field.
        /// </summary>
        internal static string fakeobjects_hiddenfield {
            get {
                return ResourceManager.GetString("fakeobjects_hiddenfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFrame.
        /// </summary>
        internal static string fakeobjects_iframe {
            get {
                return ResourceManager.GetString("fakeobjects_iframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Object.
        /// </summary>
        internal static string fakeobjects_unknown {
            get {
                return ResourceManager.GetString("fakeobjects_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Indent.
        /// </summary>
        internal static string indent_indent {
            get {
                return ResourceManager.GetString("indent_indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Indent.
        /// </summary>
        internal static string indent_outdent {
            get {
                return ResourceManager.GetString("indent_outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Key.
        /// </summary>
        internal static string link_acccessKey {
            get {
                return ResourceManager.GetString("link_acccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string link_advanced {
            get {
                return ResourceManager.GetString("link_advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory Content Type.
        /// </summary>
        internal static string link_advisoryContentType {
            get {
                return ResourceManager.GetString("link_advisoryContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory Title.
        /// </summary>
        internal static string link_advisoryTitle {
            get {
                return ResourceManager.GetString("link_advisoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type the anchor name.
        /// </summary>
        internal static string link_anchor_errorName {
            get {
                return ResourceManager.GetString("link_anchor_errorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Anchor.
        /// </summary>
        internal static string link_anchor_menu {
            get {
                return ResourceManager.GetString("link_anchor_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Name.
        /// </summary>
        internal static string link_anchor_name {
            get {
                return ResourceManager.GetString("link_anchor_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Anchor.
        /// </summary>
        internal static string link_anchor_remove {
            get {
                return ResourceManager.GetString("link_anchor_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Properties.
        /// </summary>
        internal static string link_anchor_title {
            get {
                return ResourceManager.GetString("link_anchor_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        internal static string link_anchor_toolbar {
            get {
                return ResourceManager.GetString("link_anchor_toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Element Id.
        /// </summary>
        internal static string link_anchorId {
            get {
                return ResourceManager.GetString("link_anchorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Anchor Name.
        /// </summary>
        internal static string link_anchorName {
            get {
                return ResourceManager.GetString("link_anchorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Resource Charset.
        /// </summary>
        internal static string link_charset {
            get {
                return ResourceManager.GetString("link_charset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylesheet Classes.
        /// </summary>
        internal static string link_cssClasses {
            get {
                return ResourceManager.GetString("link_cssClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Address.
        /// </summary>
        internal static string link_emailAddress {
            get {
                return ResourceManager.GetString("link_emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Body.
        /// </summary>
        internal static string link_emailBody {
            get {
                return ResourceManager.GetString("link_emailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Subject.
        /// </summary>
        internal static string link_emailSubject {
            get {
                return ResourceManager.GetString("link_emailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string link_id {
            get {
                return ResourceManager.GetString("link_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Info.
        /// </summary>
        internal static string link_info {
            get {
                return ResourceManager.GetString("link_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Code.
        /// </summary>
        internal static string link_langCode {
            get {
                return ResourceManager.GetString("link_langCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Direction.
        /// </summary>
        internal static string link_langDir {
            get {
                return ResourceManager.GetString("link_langDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left to Right (LTR).
        /// </summary>
        internal static string link_langDirLTR {
            get {
                return ResourceManager.GetString("link_langDirLTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Left (RTL).
        /// </summary>
        internal static string link_langDirRTL {
            get {
                return ResourceManager.GetString("link_langDirRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Link.
        /// </summary>
        internal static string link_menu {
            get {
                return ResourceManager.GetString("link_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string link_name {
            get {
                return ResourceManager.GetString("link_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No anchors available in the document).
        /// </summary>
        internal static string link_noAnchors {
            get {
                return ResourceManager.GetString("link_noAnchors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type the e-mail address.
        /// </summary>
        internal static string link_noEmail {
            get {
                return ResourceManager.GetString("link_noEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type the link URL.
        /// </summary>
        internal static string link_noUrl {
            get {
                return ResourceManager.GetString("link_noUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;other&gt;.
        /// </summary>
        internal static string link_other {
            get {
                return ResourceManager.GetString("link_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent (Netscape).
        /// </summary>
        internal static string link_popupDependent {
            get {
                return ResourceManager.GetString("link_popupDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Window Features.
        /// </summary>
        internal static string link_popupFeatures {
            get {
                return ResourceManager.GetString("link_popupFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen (IE).
        /// </summary>
        internal static string link_popupFullScreen {
            get {
                return ResourceManager.GetString("link_popupFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Position.
        /// </summary>
        internal static string link_popupLeft {
            get {
                return ResourceManager.GetString("link_popupLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Bar.
        /// </summary>
        internal static string link_popupLocationBar {
            get {
                return ResourceManager.GetString("link_popupLocationBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Bar.
        /// </summary>
        internal static string link_popupMenuBar {
            get {
                return ResourceManager.GetString("link_popupMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizable.
        /// </summary>
        internal static string link_popupResizable {
            get {
                return ResourceManager.GetString("link_popupResizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Bars.
        /// </summary>
        internal static string link_popupScrollBars {
            get {
                return ResourceManager.GetString("link_popupScrollBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar.
        /// </summary>
        internal static string link_popupStatusBar {
            get {
                return ResourceManager.GetString("link_popupStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        internal static string link_popupToolbar {
            get {
                return ResourceManager.GetString("link_popupToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Position.
        /// </summary>
        internal static string link_popupTop {
            get {
                return ResourceManager.GetString("link_popupTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        internal static string link_rel {
            get {
                return ResourceManager.GetString("link_rel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Anchor.
        /// </summary>
        internal static string link_selectAnchor {
            get {
                return ResourceManager.GetString("link_selectAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string link_styles {
            get {
                return ResourceManager.GetString("link_styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Index.
        /// </summary>
        internal static string link_tabIndex {
            get {
                return ResourceManager.GetString("link_tabIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string link_target {
            get {
                return ResourceManager.GetString("link_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;frame&gt;.
        /// </summary>
        internal static string link_targetFrame {
            get {
                return ResourceManager.GetString("link_targetFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Frame Name.
        /// </summary>
        internal static string link_targetFrameName {
            get {
                return ResourceManager.GetString("link_targetFrameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;popup window&gt;.
        /// </summary>
        internal static string link_targetPopup {
            get {
                return ResourceManager.GetString("link_targetPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Window Name.
        /// </summary>
        internal static string link_targetPopupName {
            get {
                return ResourceManager.GetString("link_targetPopupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string link_title {
            get {
                return ResourceManager.GetString("link_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to anchor in the text.
        /// </summary>
        internal static string link_toAnchor {
            get {
                return ResourceManager.GetString("link_toAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string link_toEmail {
            get {
                return ResourceManager.GetString("link_toEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string link_toolbar {
            get {
                return ResourceManager.GetString("link_toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string link_toUrl {
            get {
                return ResourceManager.GetString("link_toUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Type.
        /// </summary>
        internal static string link_type {
            get {
                return ResourceManager.GetString("link_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink.
        /// </summary>
        internal static string link_unlink {
            get {
                return ResourceManager.GetString("link_unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string link_upload {
            get {
                return ResourceManager.GetString("link_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert/Remove Bulleted List.
        /// </summary>
        internal static string list_bulletedlist {
            get {
                return ResourceManager.GetString("list_bulletedlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert/Remove Numbered List.
        /// </summary>
        internal static string list_numberedlist {
            get {
                return ResourceManager.GetString("list_numberedlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Toolbar.
        /// </summary>
        internal static string toolbar_toolbarCollapse {
            get {
                return ResourceManager.GetString("toolbar_toolbarCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Toolbar.
        /// </summary>
        internal static string toolbar_toolbarExpand {
            get {
                return ResourceManager.GetString("toolbar_toolbarExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Styles.
        /// </summary>
        internal static string toolbar_toolbarGroups_basicstyles {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_basicstyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard/Undo.
        /// </summary>
        internal static string toolbar_toolbarGroups_clipboard {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string toolbar_toolbarGroups_colors {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string toolbar_toolbarGroups_document {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string toolbar_toolbarGroups_editing {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string toolbar_toolbarGroups_forms {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string toolbar_toolbarGroups_insert {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string toolbar_toolbarGroups_links {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string toolbar_toolbarGroups_paragraph {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string toolbar_toolbarGroups_styles {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string toolbar_toolbarGroups_tools {
            get {
                return ResourceManager.GetString("toolbar_toolbarGroups_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor toolbars.
        /// </summary>
        internal static string toolbar_toolbars {
            get {
                return ResourceManager.GetString("toolbar_toolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string undo_redo {
            get {
                return ResourceManager.GetString("undo_redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string undo_undo {
            get {
                return ResourceManager.GetString("undo_undo", resourceCulture);
            }
        }
    }
}
