//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSauce.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JqGrid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JqGrid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalSauce.Resources.JqGrid", typeof(JqGrid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string col_bCancel {
            get {
                return ResourceManager.GetString("col_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string col_bSubmit {
            get {
                return ResourceManager.GetString("col_bSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select columns.
        /// </summary>
        public static string col_caption {
            get {
                return ResourceManager.GetString("col_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string del_bCancel {
            get {
                return ResourceManager.GetString("del_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string del_bSubmit {
            get {
                return ResourceManager.GetString("del_bSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string del_caption {
            get {
                return ResourceManager.GetString("del_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected record(s) ?.
        /// </summary>
        public static string del_msg {
            get {
                return ResourceManager.GetString("del_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Record.
        /// </summary>
        public static string edit_addCaption {
            get {
                return ResourceManager.GetString("edit_addCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string edit_bCancel {
            get {
                return ResourceManager.GetString("edit_bCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string edit_bClose {
            get {
                return ResourceManager.GetString("edit_bClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string edit_bExit {
            get {
                return ResourceManager.GetString("edit_bExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string edit_bNo {
            get {
                return ResourceManager.GetString("edit_bNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string edit_bSubmit {
            get {
                return ResourceManager.GetString("edit_bSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string edit_bYes {
            get {
                return ResourceManager.GetString("edit_bYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Record.
        /// </summary>
        public static string edit_editCaption {
            get {
                return ResourceManager.GetString("edit_editCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been changed! Save changes?.
        /// </summary>
        public static string edit_saveData {
            get {
                return ResourceManager.GetString("edit_saveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to view.
        /// </summary>
        public static string emptyrecords {
            get {
                return ResourceManager.GetString("emptyrecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string errors_errcap {
            get {
                return ResourceManager.GetString("errors_errcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of colNames&lt;&gt; colModel !.
        /// </summary>
        public static string errors_model {
            get {
                return ResourceManager.GetString("errors_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to process.
        /// </summary>
        public static string errors_norecords {
            get {
                return ResourceManager.GetString("errors_norecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nourl is set.
        /// </summary>
        public static string errors_nourl {
            get {
                return ResourceManager.GetString("errors_nourl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        public static string groupOps_op_and {
            get {
                return ResourceManager.GetString("groupOps_op_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string groupOps_op_or {
            get {
                return ResourceManager.GetString("groupOps_op_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string groupOps_text_and {
            get {
                return ResourceManager.GetString("groupOps_text_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any.
        /// </summary>
        public static string groupOps_text_or {
            get {
                return ResourceManager.GetString("groupOps_text_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loadtext {
            get {
                return ResourceManager.GetString("loadtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom function should return array!.
        /// </summary>
        public static string msg_customarray {
            get {
                return ResourceManager.GetString("msg_customarray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom function should be present in case of custom checking!.
        /// </summary>
        public static string msg_customfcheck {
            get {
                return ResourceManager.GetString("msg_customfcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter valid date value.
        /// </summary>
        public static string msg_date {
            get {
                return ResourceManager.GetString("msg_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid e-mail.
        /// </summary>
        public static string msg_email {
            get {
                return ResourceManager.GetString("msg_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter valid integer value.
        /// </summary>
        public static string msg_integer {
            get {
                return ResourceManager.GetString("msg_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value must be less than or equal to.
        /// </summary>
        public static string msg_maxValue {
            get {
                return ResourceManager.GetString("msg_maxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value must be greater than or equal to.
        /// </summary>
        public static string msg_minValue {
            get {
                return ResourceManager.GetString("msg_minValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not defined!.
        /// </summary>
        public static string msg_nodefined {
            get {
                return ResourceManager.GetString("msg_nodefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return value is required!.
        /// </summary>
        public static string msg_novalue {
            get {
                return ResourceManager.GetString("msg_novalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter valid number.
        /// </summary>
        public static string msg_number {
            get {
                return ResourceManager.GetString("msg_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string msg_required {
            get {
                return ResourceManager.GetString("msg_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid URL. Prefix required (&apos;http://&apos; or &apos;https://&apos;).
        /// </summary>
        public static string msg_url {
            get {
                return ResourceManager.GetString("msg_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nav_addtext {
            get {
                return ResourceManager.GetString("nav_addtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new row.
        /// </summary>
        public static string nav_addtitle {
            get {
                return ResourceManager.GetString("nav_addtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string nav_alertcap {
            get {
                return ResourceManager.GetString("nav_alertcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select row.
        /// </summary>
        public static string nav_alerttext {
            get {
                return ResourceManager.GetString("nav_alerttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nav_deltext {
            get {
                return ResourceManager.GetString("nav_deltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected row.
        /// </summary>
        public static string nav_deltitle {
            get {
                return ResourceManager.GetString("nav_deltitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nav_edittext {
            get {
                return ResourceManager.GetString("nav_edittext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected row.
        /// </summary>
        public static string nav_edittitle {
            get {
                return ResourceManager.GetString("nav_edittitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nav_refreshtext {
            get {
                return ResourceManager.GetString("nav_refreshtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Grid.
        /// </summary>
        public static string nav_refreshtitle {
            get {
                return ResourceManager.GetString("nav_refreshtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nav_searchtext {
            get {
                return ResourceManager.GetString("nav_searchtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find records.
        /// </summary>
        public static string nav_searchtitle {
            get {
                return ResourceManager.GetString("nav_searchtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nav_viewtext {
            get {
                return ResourceManager.GetString("nav_viewtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View selected row.
        /// </summary>
        public static string nav_viewtitle {
            get {
                return ResourceManager.GetString("nav_viewtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not begin with.
        /// </summary>
        public static string odata_bn {
            get {
                return ResourceManager.GetString("odata_bn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begins with.
        /// </summary>
        public static string odata_bw {
            get {
                return ResourceManager.GetString("odata_bw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        public static string odata_cn {
            get {
                return ResourceManager.GetString("odata_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not end with.
        /// </summary>
        public static string odata_en {
            get {
                return ResourceManager.GetString("odata_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equal.
        /// </summary>
        public static string odata_eq {
            get {
                return ResourceManager.GetString("odata_eq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        public static string odata_ew {
            get {
                return ResourceManager.GetString("odata_ew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater or equal.
        /// </summary>
        public static string odata_ge {
            get {
                return ResourceManager.GetString("odata_ge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater.
        /// </summary>
        public static string odata_gt {
            get {
                return ResourceManager.GetString("odata_gt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is in.
        /// </summary>
        public static string odata_in {
            get {
                return ResourceManager.GetString("odata_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less or equal.
        /// </summary>
        public static string odata_le {
            get {
                return ResourceManager.GetString("odata_le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less.
        /// </summary>
        public static string odata_lt {
            get {
                return ResourceManager.GetString("odata_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not contain.
        /// </summary>
        public static string odata_nc {
            get {
                return ResourceManager.GetString("odata_nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not equal.
        /// </summary>
        public static string odata_ne {
            get {
                return ResourceManager.GetString("odata_ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not in.
        /// </summary>
        public static string odata_ni {
            get {
                return ResourceManager.GetString("odata_ni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string pgtext {
            get {
                return ResourceManager.GetString("pgtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0} - {1} of {2}.
        /// </summary>
        public static string recordtext {
            get {
                return ResourceManager.GetString("recordtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string search_caption {
            get {
                return ResourceManager.GetString("search_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string search_Find {
            get {
                return ResourceManager.GetString("search_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string search_Reset {
            get {
                return ResourceManager.GetString("search_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string view_bclose {
            get {
                return ResourceManager.GetString("view_bclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Record.
        /// </summary>
        public static string view_caption {
            get {
                return ResourceManager.GetString("view_caption", resourceCulture);
            }
        }
    }
}
